apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment

spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 2
  template: 
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: k8-app
          image: mueed/eng89_app:v3
          ports:
          - containerPort: 3000